openapi: 3.0.0
info:
  title: ONDC Specification
  domain: ONDC:FIS12
  description: ONDC Specification
  version: 2.3.0
  x-usecases: 
    - BUSINESS LOAN
    - LAMF LOAN
  x-branch-name: draft-FIS12-2.3.0
  x-reporting: true
security: 
  - SubscriberAuth: []
paths:
  $ref: ./specs/openapi.yaml#/paths
components:
  $ref: ./specs/openapi.yaml#/components
x-attributes:
  $ref: ./attributes/index.yaml
x-validations:
  $ref: ./validations/index.yaml
x-errorcodes:
  $ref: ./errors/index.yaml
x-supported-actions:
  $ref: ./actions/index.yaml
x-flows:
  $ref: ./flows/index.yaml#/flows
x-docs:
  $ref: ./docs
