flows:
  - type: playground
    id: master_search
    meta:
      order: 0
    usecase: BUSINESS LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Master Search
    config:
      $ref:  "./BUSINESS_LOAN/master_search.yaml"
  - type: playground
    id: business_term_loan_with_offline_online_foreclosure
    meta:
      order: 1
    usecase: BUSINESS LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
      # - PERSONAL LOAN
    description: Business Loan - Term Loan with Offline & Online Journey (ForeClosure)
    config:
      $ref:  "./BUSINESS_LOAN/business_term_loan_with_offline_online_foreclosure.yaml"
  - type: playground
    id: business_term_loan_with_offline_online_missed_emi
    usecase: BUSINESS LOAN
    meta:
      order: 2
    tags:
      - WORKBENCH
      - REPORTABLE
      # - PERSONAL LOAN
    description: Business Loan - Term Loan with Offline & Online Journey (Missed EMI)
    config:
      $ref:  "./BUSINESS_LOAN/business_term_loan_with_offline_online_missed_emi.yaml"
  - type: playground
    id: business_term_loan_with_offline_online_pre_part
    meta:
      order: 3
    usecase: BUSINESS LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
      # - PERSONAL LOAN
    description: Business Loan - Term Loan with Offline & Online Journey(Pre Part) 
    config:
      $ref:  "./BUSINESS_LOAN/business_term_loan_with_offline_online_pre_part.yaml"        
  #LAMF
  - type: playground
    id: master_search
    meta:
      order: 0
    usecase: LAMF LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Master Search
    config:
      $ref:  "./LAMF/master_search.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey
    meta:
      order: 1
    usecase: LAMF LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF Credit Line with Offline Journey
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_single_redirection
    meta:
      order: 2
    usecase: LAMF LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF Credit Line with MFC
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc_single_redirection.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc
    meta:
      order: 3
    usecase: LAMF LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF Credit Line with MFC
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc.yaml"        
 
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey_drawdown
    meta:
      order: 4
    usecase: LAMF LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Drawdown - LAMF Credit Line with Offline Journey
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey_drawdown.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey_drawdown_foreclosure
    meta:
      order: 5
    usecase: LAMF LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Drawdown - LAMF Credit Line with Offline Journey(ForeClosure)
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey_drawdown_foreclosure.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey_drawdown_missed_emi
    meta:
      order: 6
    usecase: LAMF LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Drawdown - LAMF Credit Line with Offline Journey(Missed EMI)
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey_drawdown_missed_emi.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey_drawdown_pre_part
    meta:
      order: 7
    usecase: LAMF LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Drawdown - LAMF Credit Line with Offline Journey(Pre Part)
    config:
      $ref:  "./LAMF/lamf_credit_line_with_mfc_offline_journey_drawdown_pre_part.yaml"                
 
