flows:
  - type: playground
    id: master_search
    meta:
      order: 0
    usecase: LAMF_LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Master Search
    config:
      $ref:  "src/config/FIS12/V-2.3.0/lamf/flows/master_search.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey
    meta:
      order: 1
    usecase: LAMF_LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF Credit Line with Offline Journey
    config:
      $ref:  "src/config/FIS12/V-2.3.0/lamf/flows/lamf_credit_line_with_mfc_offline_journey.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey_drawdown
    meta:
      order: 2
    usecase: LAMF_LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Drawdown - LAMF Credit Line with Offline Journey
    config:
      $ref:  "src/config/FIS12/V-2.3.0/lamf/flows/lamf_credit_line_with_mfc_offline_journey_drawdown.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey_drawdown_foreclosure
    meta:
      order: 3
    usecase: LAMF_LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Drawdown - LAMF Credit Line with Offline Journey(ForeClosure)
    config:
      $ref:  "src/config/FIS12/V-2.3.0/lamf/flows/lamf_credit_line_with_mfc_offline_journey_drawdown_foreclosure.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey_drawdown_missed_emi
    meta:
      order: 4
    usecase: LAMF_LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Drawdown - LAMF Credit Line with Offline Journey(Missed EMI)
    config:
      $ref:  "src/config/FIS12/V-2.3.0/lamf/flows/lamf_credit_line_with_mfc_offline_journey_drawdown_missed_emi.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc_offline_journey_drawdown_pre_part
    meta:
      order: 5
    usecase: LAMF_LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Drawdown - LAMF Credit Line with Offline Journey(Pre Part)
    config:
      $ref:  "src/config/FIS12/V-2.3.0/lamf/flows/lamf_credit_line_with_mfc_offline_journey_drawdown_pre_part.yaml"                
  - type: playground
    id: lamf_credit_line_with_mfc_single_redirection
    meta:
      order: 6
    usecase: LAMF_LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF Credit Line with MFC
    config:
      $ref:  "src/config/FIS12/V-2.3.0/lamf/flows/lamf_credit_line_with_mfc_single_redirection.yaml"
  - type: playground
    id: lamf_credit_line_with_mfc
    meta:
      order: 7
    usecase: LAMF_LOAN
    tags:
      - WORKBENCH
      - REPORTABLE
    description: LAMF Credit Line with MFC
    config:
      $ref:  "src/config/FIS12/V-2.3.0/lamf/flows/lamf_credit_line_with_mfc.yaml"        
 